export enum APP_TYPES {
  START_LOGIN = "APP.START_LOGIN",
  FAILED_LOGIN = "APP.FAILED_LOGIN",
  SUCCEED_LOGIN = "APP.SUCCEED_LOGIN",
  CHANGE_CURRENT_USER = "APP.CHANGE_CURRENT_USER",
  LOGOUT = "APP.LOGOUT",
}

export enum CommonDataTypes {
  ADD_ENTITIES = "COMMON.ADD_ENTITIES",
}
